source 'https://github.com/artsy/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!

xcodeproj 'NetWorkingDemo.xcodeproj'

target :project do
    link_with 'NetWorkingDemo'
    pod 'AFNetworking', '~> 3.0'
    pod 'IQKeyboardManager', '~> 3.2'
    pod 'CocoaLumberjack', '~> 2.0'
    pod 'MagicalRecord', '~> 2.3'
    pod 'Appirater', '~> 2.0'
    pod 'MJRefresh'
    pod 'ZXingObjC', '~> 3.0'
    pod 'UMengAnalytics'
    pod 'Masonry'
    
    target :tests do
        link_with 'NetWorkingDemoTests'
        pod 'Specta', '~> 1.0'
        pod 'OCMock', '~> 3.1'
        pod 'Expecta', '~> 1.0'
    end
end